language: rust
rust:
  - stable
  - beta
  - nightly


script:
  - cargo build || travis_terminate 1
  - cargo test || travis_terminate 1
  - cargo doc || travis_terminate 1

env:
  - RUSTFLAGS="--deny warnings"

matrix:
  include:
    - name: "Check style"
      language: generic
      script: ./ci/check-basic-style.sh
    - name: "Miri tests (nightly)"
      language: rust
      rust: nightly
      script:
        - ./ci/run-miri-tests.sh || travis_terminate 1
